spring.application.name=cozyhaven
server.port = 9090
spring.datasource.url=jdbc:mysql://localhost:3306/cozyhaven
spring.datasource.username=root
spring.datasource.password=abcd@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=asdfghjklzxcvbnmmmjgskbfbsur48y545486
jwt.expiration=3600000
razorpay.key.id=rzp_test_SqlJcTJ95EZekk
razorpay.key.secret=7fWfctCFbVsGTs5LUVfQRtqc
